# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\data\basketball_outputs\anno_ui\DisplayUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1902, 916)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Open = QtWidgets.QPushButton(self.centralwidget)
        self.Open.setGeometry(QtCore.QRect(20, 780, 91, 51))
        self.Open.setObjectName("Open")
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(20, 830, 91, 28))
        self.Close.setObjectName("Close")
        self.DispalyLabel = QtWidgets.QLabel(self.centralwidget)
        self.DispalyLabel.setGeometry(QtCore.QRect(0, 0, 1400, 720))
        self.DispalyLabel.setMouseTracking(False)
        self.DispalyLabel.setObjectName("DispalyLabel")
        self.frame_begin = QtWidgets.QTextEdit(self.centralwidget)
        self.frame_begin.setGeometry(QtCore.QRect(20, 750, 91, 31))
        self.frame_begin.setObjectName("frame_begin")
        self.delete_input = QtWidgets.QTextEdit(self.centralwidget)
        self.delete_input.setGeometry(QtCore.QRect(130, 750, 111, 51))
        self.delete_input.setObjectName("delete_input")
        self.delete_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.delete_pushButton.setGeometry(QtCore.QRect(130, 800, 111, 28))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.rename_input = QtWidgets.QTextEdit(self.centralwidget)
        self.rename_input.setGeometry(QtCore.QRect(260, 750, 121, 51))
        self.rename_input.setObjectName("rename_input")
        self.rename_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.rename_pushButton.setGeometry(QtCore.QRect(260, 800, 121, 28))
        self.rename_pushButton.setObjectName("rename_pushButton")
        self.inter_input = QtWidgets.QTextEdit(self.centralwidget)
        self.inter_input.setGeometry(QtCore.QRect(540, 750, 121, 51))
        self.inter_input.setObjectName("inter_input")
        self.inter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.inter_pushButton.setGeometry(QtCore.QRect(540, 800, 121, 28))
        self.inter_pushButton.setObjectName("inter_pushButton")
        self.trans_input = QtWidgets.QTextEdit(self.centralwidget)
        self.trans_input.setGeometry(QtCore.QRect(690, 750, 121, 51))
        self.trans_input.setObjectName("trans_input")
        self.trans_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.trans_pushButton.setGeometry(QtCore.QRect(690, 800, 121, 28))
        self.trans_pushButton.setObjectName("trans_pushButton")
        self.copy_input = QtWidgets.QTextEdit(self.centralwidget)
        self.copy_input.setGeometry(QtCore.QRect(830, 750, 121, 51))
        self.copy_input.setObjectName("copy_input")
        self.copy_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.copy_pushButton.setGeometry(QtCore.QRect(830, 800, 121, 28))
        self.copy_pushButton.setObjectName("copy_pushButton")
        self.modulate_input = QtWidgets.QTextEdit(self.centralwidget)
        self.modulate_input.setGeometry(QtCore.QRect(970, 750, 121, 51))
        self.modulate_input.setObjectName("modulate_input")
        self.modulate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.modulate_pushButton.setGeometry(QtCore.QRect(970, 800, 121, 28))
        self.modulate_pushButton.setObjectName("modulate_pushButton")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(1110, 800, 81, 28))
        self.save.setObjectName("save")
        self.frame_slider = QtWidgets.QSlider(self.centralwidget)
        self.frame_slider.setGeometry(QtCore.QRect(10, 730, 160, 22))
        self.frame_slider.setMaximum(2000)
        self.frame_slider.setPageStep(100)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setInvertedAppearance(False)
        self.frame_slider.setInvertedControls(False)
        self.frame_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.frame_slider.setObjectName("frame_slider")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(1110, 750, 81, 41))
        self.select.setObjectName("select")
        self.splice_input = QtWidgets.QTextEdit(self.centralwidget)
        self.splice_input.setGeometry(QtCore.QRect(400, 750, 121, 51))
        self.splice_input.setObjectName("splice_input")
        self.splice_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.splice_pushButton.setGeometry(QtCore.QRect(400, 800, 121, 28))
        self.splice_pushButton.setObjectName("splice_pushButton")
        self.tra3d = QtWidgets.QGraphicsView(self.centralwidget)
        self.tra3d.setGeometry(QtCore.QRect(1400, 0, 501, 571))
        self.tra3d.setObjectName("tra3d")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1902, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Open.setText(_translate("MainWindow", "show video"))
        self.Close.setText(_translate("MainWindow", "stop"))
        self.DispalyLabel.setText(_translate("MainWindow", "TextLabel"))
        self.frame_begin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">起始帧</p></body></html>"))
        self.delete_pushButton.setText(_translate("MainWindow", "delete"))
        self.rename_pushButton.setText(_translate("MainWindow", "rename"))
        self.inter_pushButton.setText(_translate("MainWindow", "interpolate"))
        self.trans_pushButton.setText(_translate("MainWindow", "translate"))
        self.copy_pushButton.setText(_translate("MainWindow", "copy"))
        self.modulate_pushButton.setText(_translate("MainWindow", "modulate"))
        self.save.setText(_translate("MainWindow", "save"))
        self.select.setText(_translate("MainWindow", "select"))
        self.splice_pushButton.setText(_translate("MainWindow", "splice"))
